export {default as Home} from './Home/Home'
export {default as Navbar} from './Navbar/Navbar'
export {default as Login} from './Login/Login'
export {default as Team} from './Team/Team'
export {default as Contact} from './Contact/Contact'
export {default as About} from './About/About'
export {default as Signup} from './Signup/Signup'
export {default as Footer} from './Footer/Footer'